from My_fib import FiboHeap
a = FiboHeap()
a.MakeHeap()
b = a.insert(7)
c = a.insert(44)
d = a.insert(41)
e = a.insert(52)
f = a.insert(39)
g = a.insert(18)
h = a.insert(17)
i = a.insert(23)
j = a.insert(46)
k = a.insert(35)
l = a.insert(26)
m = a.insert(24)
n = a.insert(30)
# print(a.Minimum().data)
a.Change_Root(d,c)
a.Change_Root(g,f)
a.Change_Root(l,k)
a.Change_Root(m,l)
a.Change_Root(m,j)
a.Change_Root(b,n)
a.print_all()
a.Become_Tree()
