/* 

	Student ID: 1155080703
	
	Name: Wu Xin Yi

*/


/* Query 1 */
	
	Spool result1.lst

	SELECT LID, LEAGUE_NAME, TEAM_NAME, SEASON, YEAR FROM LEAGUES,TEAMS WHERE LEAGUES.CHAMPION_TID = TEAMS.TID AND ( LEAGUES.YEAR = 2012 OR LEAGUES.YEAR = 2013 ) ORDER BY LID ASC;

	Spool off

/* Query 2 */
   
	Spool result2.lst

	CREATE OR REPLACE VIEW temp1 AS (SELECT RID FROM LEAGUES WHERE SEASON = 'Autumn' GROUP BY RID HAVING COUNT(*) > 1 )

	SELECT REGIONS.RID, REGION_NAME, FOOTBALL_RANKING FROM temp1,REGIONS WHERE REGIONS.RID = temp1.RID ORDER BY REGIONS.RID ASC ;
	
	Spool off

/* Query 3 */
   
	Spool result3.lst

	CREATE OR REPLACE VIEW TEMP2 AS (SELECT TID FROM TEAMS WHERE AVERAGE_AGE = (SELECT MIN(AVERAGE_AGE) FROM TEAMS))

	SELECT DISTINCT LID, LEAGUE_NAME, YEAR FROM LEAGUES,TEMP2 WHERE LEAGUES.CHAMPION_TID = TEMP2.TID ORDER BY LID ASC;

	Spool off

/* Query 4 */
   
	Spool result4.lst

	//ALTER TABLE TEAMS ADD L_NUM INTEGER;

	CREATE OR REPLACE VIEW TEMP3 AS ( SELECT TID, TEAM_NAME,COUNT(*) L_NUM FROM LEAGUES, TEAMS WHERE TEAMS.TID = LEAGUES.CHAMPION_TID GROUP BY TID, TEAM_NAME )

	SELECT DISTINCT * FROM TEMP3 WHERE L_NUM > 1 ORDER BY TID DESC;

	Spool off

/* Query 5 */
   
	Spool result5.lst

	//ALTER TABLE SPONSORS ADD L_COUNT INTEGER;

	CREATE OR REPLACE VIEW TEMP4 AS ( SELECT SPONSORS.SID, SPONSOR_NAME, COUNT(*) L_Count FROM SUPPORT, SPONSORS WHERE SUPPORT.SID = SPONSORS.SID GROUP BY SPONSORS.SID, SPONSOR_NAME )

	SELECT * FROM TEMP4  ORDER BY SID DESC;

	Spool off


/* Query 6 */
   
	Spool result6.lst

	(SELECT DISTINCT SPONSORS.SID, SPONSOR_NAME 
	FROM SUPPORT,SPONSORS 
	WHERE SUPPORT.SID = SPONSORS.SID 
	GROUP BY SPONSORS.SID,SPONSOR_NAME HAVING COUNT(*) > 1)
	EXCEPT
	(SELECT DISTINCT SPONSORS.SID, SPONSOR_NAME
	FROM REGIONS, LEAGUES,SUPPORT,SPONSORS 
	WHERE REGION_NAME = 'England' AND LEAGUES.RID = REGIONS.RID AND SUPPORT.LID = LEAGUES.LID AND SUPPORT.SID = SPONSORS.SID);


	Spool off


/* Query 7 */

	Spool result7.lst

	SELECT SPONSORS.SID,SPONSOR_NAME FROM SUPPORT,SPONSORS WHERE SUPPORT.SID = SPONSORS.SID GROUP BY SPONSORS.SID,SPONSOR_NAME  HAVING SUM(SPONSORSHIP) > 2.0; 

	SELECT SPONSORS.SID,SPONSOR_NAME
	FROM REGIONS, LEAGUES,SUPPORT,SPONSORS 
	WHERE  LEAGUES.RID = REGIONS.RID AND SUPPORT.LID = LEAGUES.LID AND SUPPORT.SID = SPONSORS.SID AND REGIONS.FOOTBALL_RANKING < 10; 

	Spool off

/* Query 8 */

	Spool result8.lst

	SELECT SPONSORS.SID,SPONSOR_NAME FROM SUPPORT,SPONSORS WHERE SUPPORT.SID = SPONSORS.SID GROUP BY SPONSORS.SID,SPONSOR_NAME  HAVING SUM(SPONSORSHIP) > 2.0; 

	SELECT SPONSORS.SID,SPONSOR_NAME
	FROM REGIONS, LEAGUES,SUPPORT,SPONSORS 
	WHERE  LEAGUES.RID = REGIONS.RID AND SUPPORT.LID = LEAGUES.LID AND SUPPORT.SID = SPONSORS.SID AND REGIONS.FOOTBALL_RANKING < 10; 

	Spool off











